#ifndef BUILD_CONFIG_H
#define BUILD_CONFIG_H

#if __has_include("../../LocalBuildConfig.h")
#include "../../LocalBuildConfig.h"
#endif

#ifndef ENABLE_BLE_DIAGNOSTICS
#define ENABLE_BLE_DIAGNOSTICS 0
#endif

#ifndef USB_HOST_DEFER_UNTIL_BLE_SUBSCRIBE_MS
#define USB_HOST_DEFER_UNTIL_BLE_SUBSCRIBE_MS 15000
#endif

#ifndef USB_HOST_START_AFTER_BLE_SUBSCRIBE_DELAY_MS
#define USB_HOST_START_AFTER_BLE_SUBSCRIBE_DELAY_MS 0
#endif

#ifndef USB_HOST_ENABLE_POWER_RAILS
#define USB_HOST_ENABLE_POWER_RAILS 1
#endif

#ifndef USB_HOST_ENABLE_SEL
#define USB_HOST_ENABLE_SEL USB_HOST_ENABLE_POWER_RAILS
#endif

#ifndef USB_HOST_ENABLE_VBUS
#define USB_HOST_ENABLE_VBUS USB_HOST_ENABLE_POWER_RAILS
#endif

#ifndef USB_HOST_ENABLE_LIMIT
#define USB_HOST_ENABLE_LIMIT USB_HOST_ENABLE_POWER_RAILS
#endif

#ifndef USB_HOST_ENABLE_BOOST
#define USB_HOST_ENABLE_BOOST USB_HOST_ENABLE_POWER_RAILS
#endif

#endif  // BUILD_CONFIG_H
