#include "BongoSprites.h"

#include "sprites/body/bodyeartwitch.c"
#include "sprites/body/standardbody1.c"
#include "sprites/effects/left_click_effect.c"
#include "sprites/effects/right_click_effect.c"
#include "sprites/effects/sleepy1.c"
#include "sprites/effects/sleepy2.c"
#include "sprites/effects/sleepy3.c"
#include "sprites/faces/blink_face.c"
#include "sprites/faces/happy_face.c"
#include "sprites/faces/sleepy_face.c"
#include "sprites/faces/stock_face.c"
#include "sprites/paws/leftpawdown.c"
#include "sprites/paws/rightpawdown.c"
#include "sprites/paws/twopawsup.c"
#include "sprites/table/table1.c"
